In [1]:
import numpy as np

# Dot Product

In [2]:
def dot_product(a, b):
    dots = []
    for i,j in zip(a,b):
        dots.append(i*j)
    return sum(dots)

In [3]:
A = np.asarray([1, 5, 2, 12])
B = np.asarray([4.5, 22.1, 1.95, 1.2])

In [4]:
print(dot_product(a=A, b=B))
print(np.dot(a=A, b=B))  # using numpy

133.3
133.3


In [5]:
import time

In [6]:
A = np.asarray([1, 5, 2, 12])
B = np.asarray([4.5, 22.1, 1.95, 1.2])

In [7]:
start = time.time()
print(dot_product(a=A, b=B))
dur1 = time.time() - start

start = time.time()
print(np.dot(a=A, b=B))
dur2 = time.time() - start

dur1, dur2

133.3
133.3


(0.0004410743713378906, 0.00024819374084472656)

In [8]:
A = np.linspace(1, 1000, 10000000)
B = A/2.

start = time.time()
print(dot_product(a=A, b=B))
dur1 = time.time() - start

start = time.time()
print(np.dot(a=A, b=B))
dur2 = time.time() - start


dur1, dur2

1668335083166.7056
1668335083166.7512


(5.7598347663879395, 0.011139154434204102)

# Cross Product

If 

    u = [1, 2, 3]
    v = [4, 5, 6]

extend both using `u.extend(u[:2])` and `v.extend(v[:2])`, then you can use a simple for loop.

         x  y  z  
    u = [1, 2, 3, 1, 2]
    v = [4, 5, 6, 4, 5]

In [9]:
def cross_product(u, v):
    '''
    x_hat(u_y * v_z    -    u_z * v_y) 
    y_hat(u_z * v_x    -    u_x * v_z) 
    z_hat(u_x * v_y    -    u_y * v_x)
    '''
    u = list(u)
    v = list(v)
    n = len(u)
    u.extend(u[:2])
    v.extend(v[:2])
    croz = []
    for i in range(0,n):
        #print('%i * %i - %i * %i'%(u[i+1], v[i+2], u[i+2], v[i+1]))
        croz.append( (u[i+1] * v[i+2]) - (u[i+2] * v[i+1]) )
    return np.asarray(croz)

In [10]:
u = [1, 2, 3]
v = [4, 5, 6]
print(cross_product(u,v))
print(np.cross(u,v))    # using numpy

[-3  6 -3]
[-3  6 -3]


In [11]:
u = [5, 2, -7]
v = [9, 5, 2]
print(cross_product(u,v))
print(np.cross(u,v))

[ 39 -73   7]
[ 39 -73   7]


In [12]:
u = [12.4, -10.4663, -7.555]
v = [.9, .5, .2]
print(cross_product(u,v))
print(np.cross(u,v))

[ 1.68424 -9.2795  15.61967]
[ 1.68424 -9.2795  15.61967]


In [13]:
u = [1.432E54, 9.2E54, 7.34E53]
v = [.9, .5, .2]
print(cross_product(u,v))
print(np.cross(u,v))

[ 1.473e+54  3.742e+53 -7.564e+54]
[ 1.473e+54  3.742e+53 -7.564e+54]


In [14]:
u = [1.432E54, 9.2E54]
v = [.9, .5]
print(cross_product(u,v))
print(np.cross(u,v))

[ 7.564e+54 -7.564e+54]
-7.564e+54


In [15]:
u = [12.4, -7.555]
v = [ .5, .2]
print(cross_product(u,v))
print(np.cross(u,v))

[-6.2575  6.2575]
6.2575


In [16]:
u = [1, 2]
v = [5, 6]
print(cross_product(u,v))
print(np.cross(u,v))

[ 4 -4]
-4
